"""constants.py

Constants related to the super-resolution network.
"""

IMG_ORIG_WIDTH = 256
IMG_ORIG_HEIGHT = 240
IMG_ORIG_SIZE = (IMG_ORIG_WIDTH, IMG_ORIG_HEIGHT)

DOWNSAMPLE_FACTOR = 4

IMG_DOWN_WIDTH = IMG_ORIG_WIDTH // DOWNSAMPLE_FACTOR
IMG_DOWN_HEIGHT = IMG_ORIG_HEIGHT // DOWNSAMPLE_FACTOR
IMG_DOWN_SIZE = (IMG_DOWN_WIDTH, IMG_DOWN_HEIGHT)

BATCH_SIZE = 32

RESIZE_METHOD = "gaussian"
