# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QNKGtjodP8dzQJoWCuwsRfGZNIzD_yAJ
"""

import torch
import torch.nn.functional as func

import train
import dataset
import modules

def test(model, adj, features, target):
    model.eval()
    output = model(features, adj)
    loss_test = func.nll_loss(output[test_ds], target[test_ds])
    acc_test = accuracy(output[test_ds], target[test_ds])
    print("loss= {:.4f}".format(loss_test.item()),
          "accuracy= {:.4f}".format(acc_test.item()))

data = load_data()
train_ds, valid_ds, test_ds, features, target, edges = process_data(dataset)
model = model_init(features, data)
adj = adj_matrix(data)
test(model, adj, features, target)