# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1plzAcum7DFj_LEwRmmT0kOrIKJRoghus
"""

from dataset import *
from modules import *
from keras import backend as K
import matplotlib.pyplot as plt

# Unet model is being called from the file modules
model = unet_model()

smooth = 1e-15
def dice_coef(y_true, y_pred):
    y_true = tf.keras.layers.Flatten()(y_true)
    y_pred = tf.keras.layers.Flatten()(y_pred)
    intersection = tf.reduce_sum(y_true * y_pred)
    return (2. * intersection + smooth) / (tf.reduce_sum(y_true) + tf.reduce_sum(y_pred) + smooth)

def dice_loss(y_true, y_pred):
    return 1.0 - dice_coef(y_true, y_pred)

model.compile(optimizer='adam', loss="dice_loss", metrics=['dice_coef'])
model.summary()

model.fit(X_train_image, Y_train_mask, batch_size=8, epochs=3,
               validation_data=(X_validate_image, Y_validate_mask))

model.save("UNET_Model")