# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V0NURd0ow2kOjwaCWiKARFgxRr7jpZij
"""

#Author : Vaibhavi Itkyal
#Student ID : s4596970

import matplotlib.pyplot as plt
from skimage import data
import tensorflow as tf

image = data.camera()
#plt.imshow(image, cmap='gray')
#print(image.shape)

def plot_edges(option):
  if (option=='1'):
    display_h = sobel_horizontal(image)
    plt.imshow(display_h[0, :, :, 0], cmap='gray') #Horizontal Edges
  elif (option=='2'):
    display_v = sobel_vertical(image)
    plt.imshow(display_v[0, :, :, 0], cmap='gray') #Vertical Edges
  elif (option=='3'):
    display_h = sobel_horizontal(image)
    display_v = sobel_vertical(image)
    display = ((display_v**2) + (display_h**2))**0.5 #computing edge magnitude 
    plt.imshow(display[0, :, :, 0], cmap='gray') #Edge Magnitude
  else:
    print('Please choose a number from 1,2,3 only.')

#Driver Script
if __name__ == "__main__":

  print('Choose the number corresponding to the image transformation you want')
  print('1. Horizontal edges of an image using Sobel Transform\n2. Vertical edges of an image using Sobel Transform\n3. Edge Magnitiude using Sobel Transform')
  number = input()

  plot_edges(number)

