"""
utils.py

Alex Nicholson (45316207)
11/10/2022

Contains extra utility functions to help with this like results visualisation and saved model loading

"""


import matplotlib as plt


def show_subplot(original, reconstructed):
    """
    Shows a series of tiled plots with side-by-side examples of the original data and reconstructed data

        Parameters:
            original (ndarray): An example of an original image from the training dataset
            reconstructed (ndarray): A new synthetic image generated by the VQ-VAE model
    """

    plt.subplot(1, 2, 1)
    plt.imshow(original.squeeze() + 0.5)
    plt.title("Original")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(reconstructed.squeeze() + 0.5)
    plt.title("Reconstructed")
    plt.axis("off")

    plt.show()



