weights: yolov5m.pt
cfg: ''
data: /home/medicalrobotics/PatternFlow_LC/recognition/s4532810-YOLO-xspinella/yolov5_LC/data/ISIC_dataset.yaml
hyp:
  lr0: 0.00334
  lrf: 0.15135
  momentum: 0.74832
  weight_decay: 0.00025
  warmup_epochs: 3.3835
  warmup_momentum: 0.59462
  warmup_bias_lr: 0.18657
  box: 0.02
  cls: 0.21638
  cls_pw: 0.5
  obj: 0.51728
  obj_pw: 0.67198
  iou_t: 0.2
  anchor_t: 3.3744
  anchors: 3.412
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 5.0
  translate: 0.15
  scale: 0.9
  shear: 5.0
  perspective: 0.001
  flipud: 0.5
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.1
  copy_paste: 0.1
epochs: 450
batch_size: -1
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: yolov5_LC/runs/train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: yolov5_LC/runs/train/exp3
