import torch
import cv2
from PIL import Image

def load_model(path='best.pt'):
    """"
    Loads a PyTorch model generated by YOLOv5.

    Parameters:
        path - The path to the .pt file (currently set to best.pt in the current directory)

    Returns:
        A PyTorch model
    """
    model = torch.hub.load('ultralytics/yolov5', 'custom', path=path, force_reload=True)
    return model

def predict(model, image_path):
    """
    Provides inference using a given model on a given image. Saves the image with predictions on it
    to a folder called 'runs'.

    Parameters:
        model: A PyTorch model
        image_path: Path to image to perform inference on
 
    Returns:
        None
    """
    im = Image.open(image_path)
    results = model(im)
    results.save()


