TRAIN_DATA_PATH = 'D:/UQ/Fourth Sem/Pattern-Analysis/Prac2/keras_png_slices_data/keras_png_slices_train'
VALIDATE_DATA_PATH = 'D:/UQ/Fourth Sem/Pattern-Analysis/Prac2/keras_png_slices_data/keras_png_slices_validate'
TEST_DATA_PATH = 'D:/UQ/Fourth Sem/Pattern-Analysis/Prac2/keras_png_slices_data/keras_png_slices_test'
VQ_CHECKPOINT_PATH = 'vq_vae/cp-{epoch:04d}.ckpt'
PRIOR_CHECKPOINT_PATH = 'vq_prior/cp-{epoch:04d}.ckpt'
TRAINED_VQ_PATH = 'vq_vae/cp-0100.ckpt'
TRAINED_PRIOR_PATH = 'vq_prior/cp-0100.ckpt'