# -*- coding: utf-8 -*-
"""modules.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yf91FX1BH1RnqgobIglUXLOuvSwy2Vc9
"""

import tensorflow as tf
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Conv2DTranspose, Cropping2D, Concatenate, Dropout, Layer

class ContextModule(Layer):
  def __init__(self, filters):
    super(ContextModule, self).__init__()
    self.convA = Conv2D(filters = filters,
                        kernel_size = (3,3))
    self.convB = Conv2D(filters = filters,
                        kernel_size = (3,3))
    self.dropout = Dropout(0.3)
  def call(self, inputs):
    x = self.convA(inputs)
    x = self.convB(x)
    return self.dropout(x)

class LocalizationModule(Layer):
  def __init__(self, filters):
    super(LocalizationModule, self).__init__()
    self.convA = Conv2D(filters = filters,
                        kernel_size = (3,3))
    self.convB = Conv2D(filters = filters,
                        kernel_size = (1,1))
  def call(self, inputs):
    x = self.convA(inputs)
    return self.convB(x)
