# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MnYUCM4kvdRT1U7XTIEhg0nyTIQfBVnV
"""

!pip install kora -q

from kora import drive
drive.link_nbs()

import tensorflow as tf
import dataset 
import modules

def train():
  seg_train_path = '/content/drive/MyDrive/ISIC/ISIC-2017_Training_Part1_GroundTruth'
  train_path = '/content/drive/MyDrive/ISIC/ISIC-2017_Training_Data'
  seg_test_path = '/content/drive/MyDrive/ISIC/ISIC-2017_Test_v2_Part1_GroundTruth'
  test_path = '/content/drive/MyDrive/ISIC/ISIC-2017_Test_v2_Data'
  seg_val_path = '/content/drive/MyDrive/ISIC/ISIC-2017_Validation_Part1_GroundTruth'
  val_path = '/content/drive/MyDrive/ISIC/ISIC-2017_Validation_Data'
  print("checkpoint 1")
  xtrain, ytrain = dataset.load_dataset(train_path, seg_train_path)
  print("checkpoint 2")
  xval, yval = dataset.load_dataset(val_path, seg_val_path)
  print("checkpoint 3")
  xtest, ytest = dataset.load_dataset(test_path, seg_test_path)
  print("checkpoint 4")
  model = modules.ImprovedUnet()
  model.compile(optimizer='adam', loss='binary_crossentropy', metrics=[modules.dice_similarity])
  print("checkpoint 5")
  model.summary()
