# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MnYUCM4kvdRT1U7XTIEhg0nyTIQfBVnV
"""

!pip install kora -q

from kora import drive
drive.link_nbs()

import tensorflow as tf
import dataset 
import modules

def train(xtrain, ytrain, xval, yval):
  model = modules.improved_unet()
  model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=[modules.dice_similarity])
  history = model.fit(xtrain, ytrain, batch_size=2, epochs=50, validation_data=(xval, yval))
  model.save('improved_unet.model', save_format='h5')
  return model, history

seg_train_path = '/content/drive/MyDrive/ISIC/test_train_segmented'
train_path = '/content/drive/MyDrive/ISIC/test_train'
#seg_test_path = '/content/drive/MyDrive/ISIC/ISIC-2017_Test_v2_Part1_GroundTruth'
#test_path = '/content/drive/MyDrive/ISIC/ISIC-2017_Test_v2_Data'
seg_val_path = '/content/drive/MyDrive/ISIC/test_val_segmented'
val_path = '/content/drive/MyDrive/ISIC/test_val'
xtrain, ytrain = dataset.load_dataset(train_path, seg_train_path)
xval, yval = dataset.load_dataset(val_path, seg_val_path)
#xtest, ytest = dataset.load_dataset(test_path, seg_test_path)

train(xtrain, ytrain, xval, yval)