# -*- coding: utf-8 -*-
"""adjusted_dice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WeRZvV6xaxwLb_3K2dK6cbaxO4zAx0QY
"""

def dice_coef(y_true, y_pred):
    
    intersection = tf.reduce_sum(y_true * y_pred, axis=[1,2])
    joint = tf.reduce_sum(y_true, axis=[1,2]) + tf.reduce_sum(y_pred, axis=[1,2])
    lose = (2. * intersection) / (union + 1e-6)
    return tf.reduce_mean(loss, axis=0)