# -*- coding: utf-8 -*-
"""COMP3702_UNet_ISIC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F-1aAkPv29pH6VJSzzeJ6n-twuxkQGyO

The following two code blocks are similar to my Demo2 code.
"""

# Start by importing dependencies.

import pathlib
import os
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
#from google.colab import drive
from tensorflow.keras.preprocessing.image import load_img
import PIL.Image

print(tf.__version__)

# Some stuff to bug fix.


img_size_params = (128, 128, 3)

# Start by creating a basic U-NET model.

def get_UNET_model(img_size_params, num_classes):
    inputs = keras.Input(shape=img_size_params)

    ### [First half of the network: downsampling inputs] ###

    # Entry block
    x = layers.Conv2D(32, 3, strides=2, padding="same")(inputs)
    x = layers.UpSampling2D(size=(2,2))(x)
    outputs = layers.Conv2D(num_classes, 1, activation="sigmoid", padding="same")(x)

    # Define the model
    model = keras.Model(inputs, outputs)
    return model

model = get_UNET_model(img_size_params, 1)