# -*- coding: utf-8 -*-
"""COMP3702_UNet_ISIC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F-1aAkPv29pH6VJSzzeJ6n-twuxkQGyO

The following two code blocks are similar to my Demo2 code.
"""

# Start by importing dependencies.

import pathlib
import os
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from google.colab import drive

print(tf.__version__)

# Some stuff to bug fix.

physical_devices = tf.config.experimental.list_physical_devices('GPU')
assert len(physical_devices) > 0, "Not enough GPU hardware devices available"
config = tf.config.experimental.set_memory_growth(physical_devices[0], True)
# os.getcwd()
drive.mount('/content/gdrive')

# Import the data files from Google Drive to colab.

# Pre-process the data.